- name: "Apache installation using docker"
  hosts: prod
  become: true
  pre_tasks:
    - name: Install EPEL GIT and WGET
      yum: 
        name: "{{ item }}"
        state: present
      with_items:
        - epel-release      
        - wget
        - git
      when: ansible_distribution == "CentOS"
    - name: download pip script
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py
    - name: install python-pip
      command: python2.7 /tmp/get-pip.py
    - name: Install docker python
      pip: name=docker-py
  tasks:
    - name: Custom site
      template:
        src: index.html.j2
        dest: /tmp/index.html
    - name: Create Apache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
        volumes:
          - /tmp/index.html:/usr/local/apache2/htdocs/index.html
